package AidanAzkafaroDesonJmartFH.jmart_android.model;

public enum ProductCategory
{
    BOOK, KITCHEN, ELECTRONIC, FASHION, GAMING, GADGET, MOTHERCARE, COSMETICS,
    HEALTHCARE, FURNITURE, JEWELRY, TOYS, FNB, STATIONARY, SPORTS, AUTOMOTIVE,
    PETCARE, ART_CRAFT, CARPENTARY, MISCELLANEOUS, PROPERTY, TRAVEL, WEDDINNG

}